apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: exoscale-automation

resources:
  - deployment.yaml

configMapGenerator:
  - name: dbaas-filter-script
    files:
      - exo-dbaas-filter.sh

generatorOptions:
  disableNameSuffixHash: true
